# Generated by Django 5.1.4 on 2024-12-22 10:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
